### ISSUE TITLE
Add issue (and PR) templates with user-friendly fields.

### ISSUE THREAD

**Issue by TechStudent11** [ThioJoe/YouTube-Spammer-Purge#105]
I've seen GitHub experiment with Issue and Pull Request templates. It's actually very cool! What happens is instead of copying and pasting the template Markdown file, if you use a `.yml` (Yaml) file, it gives you actual fields! This is apparent in the [`electron/electron`](https://github.com/electron/electron) repository.

_Electron Issue Template_

![image](https://user-images.githubusercontent.com/76978184/144504774-67ae508f-19d5-4d2f-ac7d-fad586f3b45b.png)

I feel like this would be more user-friendly because @ThioJoe is targeting creators and most creators have probably never worked with Markdown on GitHub.

_Originally posted by @TechStudent11 in https://github.com/ThioJoe/YouTube-Spammer-Purge/pull/104#pullrequestreview-822031848_

**Comment by ThioJoe** [comment]
Hm very interesting, I'll look into it. Would definitely made things way easier.

**Comment by TechStudent11** [comment]
@ThioJoe One, THAT WAS QUICK. Second, I haven't tried this out myself ('cause I don't know Yaml), but I think this would improve this greatly.

**Comment by TechStudent11** [comment]
Also, maybe a website could be in order and it could automatically open a GitHub issue and if anyone replies, they get an email. This would require not only creating a new GitHub account but a whole new email!

**Comment by KendallDoesCoding** [comment]
> Also, maybe a website could be in order and it could automatically open a GitHub issue and if anyone replies, they get an email. This would require not only creating a new GitHub account but a whole new email!

This seems like a good idea!

**Comment by TechStudent11** [comment]
@KendallDoesCoding That's right. @ThioJoe would need spam protection against an app that is made to clear spam of a website that already has bad spam protection.

**Comment by TechStudent11** [comment]
I just found a template for the user-friendly issue templates.

```yaml
name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
```

You should be able to modify this to your liking.

cc. @KendallDoesCoding @ThioJoe
